service:
  name: log-aggregator
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "logs:*"
      Resource: "*"
  profile: privat

functions:
  log-aggregator:
    handler: index.handler
    timeout: 60
    memorySize: 128
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
